### ISSUE TITLE
RuntimeError: The size of tensor a (32000) must match the size of tensor b (32001) at non-singleton dimension 0

### ISSUE THREAD

**Issue by gqjia** [dandelionsllm/pandallm#1]
Traceback (most recent call last):
  File "/panda/apply_delta.py", line 171, in <module>
    apply_delta(args.base_model_path, args.target_model_path, args.delta_path)
  File "/panda/apply_delta.py", line 146, in apply_delta
    param.data += delta.state_dict()[name]
RuntimeError: The size of tensor a (32000) must match the size of tensor b (32001) at non-singleton dimension 0

**Comment by SparkJiao** [comment]
Now fixed. Try it again after `git pull`.

Thanks!
