### ISSUE TITLE
请问4090单卡可以完成7B模型的训练吗

### ISSUE THREAD

**Issue by mircop1t** [dandelionsllm/pandallm#11]
如题，求大佬解答

**Comment by ltz0120** [comment]
Finetune基本不行，可以考虑lora

**Comment by SparkJiao** [comment]
如果你数据量比较少的话 可以考虑用gradient checkpointing + cpu offload （在deepspeed config里开启） 然后酌情减少输入序列的最大长度。当然这样会非常慢，小数据的话还算能接受。

**Comment by mircop1t** [comment]
> 如果你数据量比较少的话 可以考虑用gradient checkpointing + cpu offload （在deepspeed config里开启） 然后酌情减少输入序列的最大长度。当然这样会非常慢，小数据的话还算能接受。

请问如果两张4090卡可以完成训练吗

**Comment by SparkJiao** [comment]
跑起来训练没问题 但是时间成本需要你自己衡量
