### ISSUE TITLE
推理超参数

### ISSUE THREAD

**Issue by suolyer** [dandelionsllm/pandallm#17]
hi～，很好的工作，想问下有没有 inference 的代码示例：
1）比如 prompt 的构造，需不需要🏠 Human,Bot等
2）generate 的参数，temperature，top_p,top_k等

我自己generate的效果比较差

**Comment by SparkJiao** [comment]
Hi, 感谢关注
1. 不需要特别的前缀，你可以在数据集里的py文件里找到一些默认的prompt。推荐使用COIG系列的模型，会有更好的instruction following的能力
2. generate我没有加过多的设置，我自己的经验是用greedy search即可，beam search和sampling都可能会让结果变差。
