### ISSUE TITLE
linly预训练阶段和panda类似，指令微调阶段使用了500万条，为什么效果比panda差？

### ISSUE THREAD

**Issue by mellivoraPKU** [dandelionsllm/pandallm#20]
是因为你们对比的是linly的基础模型，而不是他们经过指令微调的linly-chatflow吗？7b

**Comment by SparkJiao** [comment]
是的，在测试时他们使用instruction tuning的HF权重并没有放出来（但是放出了Tencent Pretrain权重），所以没有评测，我们在README里已经说明了。

之后会连同MOSS，ChatGLM，包括BELLE最好的模型一起补测。
