### ISSUE TITLE
如何将COIG数据集处理为instruction tuning的格式

### ISSUE THREAD

**Issue by HuihuiChyan** [dandelionsllm/pandallm#24]
如题，COIG一共由六个文件组成，每个文件的输入都不太一样。特别的，对于counterfactual_correction_multi_round_chat这个文件而言，会处理成什么形式呢？这个文件的哪一部分作为了instruction tuning的输入和输出呢？
![image](https://github.com/dandelionsllm/pandallm/assets/29159002/d570b9ac-de63-42b9-9db6-9877064d2c1a)

**Comment by SparkJiao** [comment]
I have udpated with a notebook for processing COIG data:

`https://github.com/dandelionsllm/pandallm/blob/main/unify_format.ipynb`
