### ISSUE TITLE
商用7b模型，直接进行推理说话毫无逻辑，难道不是开箱即用的嘛？

### ISSUE THREAD

**Issue by Goo-goo-goo** [dandelionsllm/pandallm#26]
![微信图片_20230606141643](https://github.com/dandelionsllm/pandallm/assets/40024222/df1862ae-9b9b-4580-a8f1-fc37952c1e74)
还出现乱码情况，求解答，

**Comment by SparkJiao** [comment]
OpenLLaMA的预训练token比较少所以能力不太够强
另外我们没有给他很多对话的数据进行训练，以百科和问答为主，以及少量的代码相关的指令。
不要期望他能和你进行多轮对话，你可以问他一些比较明确的问题，比如“迈克尔乔丹是谁？“或者“阅读以下文章，回答问题：<文章> <问题>”等

**Comment by Goo-goo-goo** [comment]
好的吧 谢谢你

**Comment by SparkJiao** [comment]
库里有13B的 可以试试 另外使用了更多对话和指令数据的13B模型以及65B-lora模型近期会开源 可以等一下 大概一周以内

**Comment by Goo-goo-goo** [comment]
嗯嗯嗯 非常感谢
