### ISSUE TITLE
RuntimeError: The size of tensor a (32000) must match the size of tensor b (32001) at non-singleton dimension 0 

### ISSUE THREAD

**Issue by jeinlee1991** [dandelionsllm/pandallm#31]
运行apply_delta.py。合并权重的时候报这个错误！经过查看，发现Panda-Instruct-7B的vocab_size是32001，而官方llama的vocab_size是32000。怎么破？

**Comment by SparkJiao** [comment]
这个问题应该很早之前就Fix过了，能否请你检查一下是否使用的是我们repo下最新版的`apply_delta.py`？

**Comment by jeinlee1991** [comment]
@SparkJiao 是的，用最新的apply_delta.py运行正常，谢谢~
