### ISSUE TITLE
Panda-LLaMA2-13B的模型链接不对吧？

### ISSUE THREAD

**Issue by sun1092469590** [dandelionsllm/pandallm#33]
您好，项目中有给Panda-LLaMA2-13B模型的链接，进去看着不对，前两个月更新的，应该不是llama2吧？请问有可开源的链接吗？

**Comment by SparkJiao** [comment]
你好，llama2的链接还没有放上去，目前Chat版本还在训练，普通版本正在上传，上传后会先更新。

**Comment by sun1092469590** [comment]
> 你好，llama2的链接还没有放上去，目前Chat版本还在训练，普通版本正在上传，上传后会先更新。

哇，太好的，期待期待

**Comment by SparkJiao** [comment]
https://huggingface.co/qcw/llama2-panda-zh-13b

这是Llama非chat版本的权重。不过目前训练步数不是很多 大概是Llama-1的一半。之后会resume。
