### ISSUE TITLE
关于评估选用的BELLE baseline问题

### ISSUE THREAD

**Issue by hejujie** [dandelionsllm/pandallm#4]
想问下这边评估选用的是左边红色的open-dataset模型，还是右边的ext模型。
如果按照这readme的名字，应该是用的右边的模型，这个ext的模型应该是刚扩完词表的，open-datasets才是它们论文里面的最优模型。不确定是否这里就是只是想测试ext的效果。
![image](https://user-images.githubusercontent.com/29149911/236389305-0a0c425b-a542-4cd4-9ac8-0cb1bb02ad1a.png)
对应的BELLE论文中的表格（绿色为ext，红色为open-datasets）：
![image](https://user-images.githubusercontent.com/29149911/236389149-a569925c-79e2-48a3-9463-243be164429b.png)

**Comment by SparkJiao** [comment]
感谢提醒，我看到模型的名字都叫EXT所以以为LLaMA-EXT-7B就是论文中最好的模型。我们会尽快补充相关模型的实验并测试，谢谢你的反馈！
