### ISSUE TITLE
模型合并推理结果不正常

### ISSUE THREAD

**Issue by xxxxuee** [dandelionsllm/pandallm#5]
使用了LLaMA HF版本的权重和[llama-panda-zh-coig-7b-delta]做合并，预测的效果比较差。
![image](https://user-images.githubusercontent.com/26203964/236418754-0baf280a-c438-4a4a-9af1-de3f3af32e04.png)

**Comment by SparkJiao** [comment]
Hi，之前的合并代码有点问题，不确定是否合并成功，可以拉一下最新的代码再试试。另外我用合并后的代码测试了你的例子，结果放在下面：

![image](https://user-images.githubusercontent.com/16469472/236436474-c0916aef-0095-4403-bf53-fa4c6a5b6912.png)

确实这个模型在短chat方面表现并不好，原因可能是因为COIG和pre-train的数据还是以任务导向为主，问答和翻译为主。对于第二个例子模型能够给出答案，例子里也测试了是否开启beam search的情况。不过这个题目我本身也不太清楚答案是什么，所以不知道哪个是对的。目前7B的模型能力还是很欠缺，13B训好以后我们会尽快release权重并在更多benchmark上测试。

Thanks!

**Comment by jeinlee1991** [comment]
@SparkJiao    Panda-Instruct-7B, 我遇到类似的推理问题，结果看起来很不正常，举例：
1、[input]: 你是谁
      [output]: 我是谁
2、[input]: 你采用什么模型
     [output]: 来处理这个问题？ 这个问题可以使用逻辑回归模型来处理。

不知道模型加载有没有问题。如果确定模型无误的话，那么这样的效果难以做chat啊，和belle-llama-7b有明显差距。

**Comment by lucasjinreal** [comment]
![image](https://github.com/dandelionsllm/pandallm/assets/21303438/f5a40f68-7f8e-48e0-925e-f53df5d8eded)

**Comment by jeinlee1991** [comment]
> ![image](https://user-images.githubusercontent.com/21303438/245746974-f5a40f68-7f8e-48e0-925e-f53df5d8eded.png)

这个效果看起来正常，方便把推理代码贴出来嘛？

**Comment by lucasjinreal** [comment]
这个是我们自己的训的模型

**Comment by SparkJiao** [comment]
@jeinlee1991  前面已经回复过了，COIG微调的模型就是没法Chat，是用来做任务的，我们现在有13B用于Chat的模型，对话效果很不错，可以在Telegram上试用，链接在这里：https://t.me/PandaLLMChat_bot
![38f5396722ac0ed90fb00d146e7e740](https://github.com/dandelionsllm/pandallm/assets/16469472/918b2bdb-6e9c-4bfb-a49b-f3419ac5ea45)
![3eaf498105298d8beeb84cfc0cc36a4](https://github.com/dandelionsllm/pandallm/assets/16469472/6a5a83bb-6e51-42d6-9143-ad0cc365408f)
![edfca2549cd2897780ea321b2609cec](https://github.com/dandelionsllm/pandallm/assets/16469472/ab8194e4-592b-424c-b003-8b79e6de71c5)
![0d44b9ea00db9f4263064ddcd0f7e92](https://github.com/dandelionsllm/pandallm/assets/16469472/a500f906-494f-4a2d-a402-b25c08c4cf64)

这里有一些例子可以参考

另外 @lucasjinreal 这位同学 在别人家的Repo下面打自己家的广告不是很好哈 你们可以去社交平台上宣传自己

**Comment by lucasjinreal** [comment]
@SparkJiao  我既没有列出我模型名字，也没有列出任何相关信息，不存在广告不广告。

另外阿凡达2009年才首次上映啊。（无意冒犯，纠正个事实哈）

![image](https://github.com/dandelionsllm/pandallm/assets/21303438/63908d8b-f104-4b6e-b1f2-fc731e5f68a8)

**Comment by jeinlee1991** [comment]
> @jeinlee1991 前面已经回复过了，COIG微调的模型就是没法Chat，是用来做任务的，我们现在有13B用于Chat的模型，对话效果很不错，可以在Telegram上试用，链接在这里：https://t.me/PandaLLMChat_bot ![38f5396722ac0ed90fb00d146e7e740](https://user-images.githubusercontent.com/16469472/245781910-918b2bdb-6e9c-4bfb-a49b-f3419ac5ea45.jpg) ![3eaf498105298d8beeb84cfc0cc36a4](https://user-images.githubusercontent.com/16469472/245781950-6a5a83bb-6e51-42d6-9143-ad0cc365408f.jpg) ![edfca2549cd2897780ea321b2609cec](https://user-images.githubusercontent.com/16469472/245781981-ab8194e4-592b-424c-b003-8b79e6de71c5.jpg) ![0d44b9ea00db9f4263064ddcd0f7e92](https://user-images.githubusercontent.com/16469472/245782087-a500f906-494f-4a2d-a402-b25c08c4cf64.png)
> 
> 这里有一些例子可以参考
> 
> 另外 @lucasjinreal 这位同学 在别人家的Repo下面打自己家的广告不是很好哈 你们可以去社交平台上宣传自己

后续会开放chat模型下载吗？很期待！

**Comment by SparkJiao** [comment]
@jeinlee1991 会开放的，现在还在只训练了一半左右，跑完所有数据之后会放出权重。月底之前。

**Comment by jeinlee1991** [comment]
> @jeinlee1991 会开放的，现在还在只训练了一半左右，跑完所有数据之后会放出权重。月底之前。

好的，谢谢！期待……

**Comment by SparkJiao** [comment]
@jeinlee1991 13B-Chat的权重开放，可以参考README下载。目前只是中间版本。全部训练完成之后会发布新的权重。
