### ISSUE TITLE
推理的效果很奇怪，能否帮忙看一下原因

### ISSUE THREAD

**Issue by ccyhxg** [dandelionsllm/pandallm#9]
直接用huggingface的pipeline推理无法使用GPU，
然后示例代码如下：
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("chitanda/llama-panda-zh-coig-7b-delta")
model = AutoModelForCausalLM.from_pretrained("chitanda/llama-panda-zh-coig-7b-delta")
model.cuda()
prompt = "<|Human|>:你好\n<|bot|>:"
inputs = tokenizer(prompt, return_tensors='pt').to('cuda')
del inputs["token_type_ids"]
tokens = model.generate(
 **inputs,
 max_new_tokens=256,
 do_sample=True,
 temperature=1.0,
 top_p=1.0,
)
print(tokenizer.decode(tokens[0], skip_special_tokens=True))
结果很奇怪
![image](https://user-images.githubusercontent.com/103231034/236611440-d9914138-a632-41f8-bc8b-f2290a7036c7.png)

**Comment by SparkJiao** [comment]
`chitanda/llama-panda-zh-coig-7b-delta`是我们权重与LLaMA原版权重的差值，不能直接做推理，需要先与原始LLaMA的HF版本权重合并后再推理。

可以参考目录下`apply_delta.py`先进行合并，脚本文件最上端有注释提醒如何使用。

**Comment by SparkJiao** [comment]
另外我们的模型在训练的时候没有使用诸如`<|Human|>, <|Bot|>`之类的前缀，所以不需要加这些， 直接输入指令即可。
